### ISSUE TITLE
ALTER / Move-and-Copy

### ISSUE THREAD

**Issue by ofbeaton** [clutchski/caribou#10]
This is a feature request.

SQLITE does not support many of the ALTER statements we are used to in other RDBMS. It would be great if Caribou helped us do effortless ALTERs by doing the move-and-copy workaround for us. It could batch the alters together so that only a single move-and-copy would need to be executed.

I understand that I can do this today by implementing a migration that does this myself, but there may be room for Caribou to provide helper functions to make such a task less error prone / easier / more efficient, especially to those less familiar with this pattern.

I also understand if this is outside the intended scope of caribou, as it presents less "simple" and more "advanced/smart" feature beyond just the migration.

For an example of what I mean, you can check [SQLAlchemy's Alembic project ](https://github.com/sqlalchemy/alembic) which implements this specifically for SQLite databases and is MIT licensed.

**Comment by clutchski** [comment]
Hi!

I think it's out of scope for this. You can use sqlalchemy in your own migration if you want. It doesn't need to be reimplemented here.

Thanks!
